### ISSUE TITLE
Actividad 7 Diego Cruz Cruz

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-7-Diegocruz040708#1]
[Linea del tiempo Diego CC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Diegocruz040708/files/9804153/Linea.del.tiempo.Diego.CC.pdf)

Diego Cruz Cruz 
Grupo 1bs
Act7

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 18.8% de un 20%, esto debido a la falta de organización de información misma que actúa en la dificultad de lectura y entendimiento a la dirección de la línea

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
